version: '3.3'
services:
    game:
      build: .
    mysqldb:
      image: mysql:latest
      environment:
        MYSQL_DATABASE: 'test'
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'root'
      ports:
        - '3309:3306'
